apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agentops.fullname" . }}-secret
  labels: {{- include "agentops.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.postgres.password | quote }}
